version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/public
    sync: true
    matcher:
      files: "public/**"

  - label: area/layouts
    sync: true
    matcher:
      files: "src/layouts/**"

  - label: area/styles
    sync: true
    matcher:
      files: "src/styles/**"

  - label: area/store
    sync: true
    matcher:
      files: "src/store/**"

  - label: area/blocks
    sync: true
    matcher:
      files: "src/pages/blocks/**"

  - label: area/transactions
    sync: true
    matcher:
      files: "src/pages/transactions/**"

  - label: area/masternodes
    sync: true
    matcher:
      files: "src/pages/masternodes/**"

  - label: area/oracles
    sync: true
    matcher:
      files: "src/pages/oracles/**"

  - label: area/tokens
    sync: true
    matcher:
      files: "src/pages/tokens/**"

  - label: area/dex
    sync: true
    matcher:
      files: "src/pages/dex/**"
