version: v1

labels:
  - label: kind/feature
    sync: true
    matcher:
      title: "^feat\\(.+\\): .+"

  - label: kind/feature
    sync: true
    matcher:
      title: "^feature\\(.+\\): .+"

  - label: kind/fix
    sync: true
    matcher:
      title: "^fix\\(.+\\): .+"

  - label: kind/chore
    sync: true
    matcher:
      title: "^chore\\(.+\\): .+"

  - label: kind/refactor
    sync: true
    matcher:
      title: "^refactor\\(.+\\): .+"

  - label: kind/docs
    sync: true
    matcher:
      title: "^docs\\(.+\\): .+"

  - label: kind/dependencies
    sync: true
    matcher:
      title: "^bump(\\(.+\\))?: .+"

  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/public
    sync: true
    matcher:
      files: "public/**"

  - label: area/layouts
    sync: true
    matcher:
      files: "src/layouts/**"

  - label: area/styles
    sync: true
    matcher:
      files: "src/styles/**"

  - label: area/store
    sync: true
    matcher:
      files: "src/store/**"

  - label: area/blocks
    sync: true
    matcher:
      files: "src/pages/blocks/**"

  - label: area/transactions
    sync: true
    matcher:
      files: "src/pages/transactions/**"

  - label: area/masternodes
    sync: true
    matcher:
      files: "src/pages/masternodes/**"

  - label: area/oracles
    sync: true
    matcher:
      files: "src/pages/oracles/**"

  - label: area/tokens
    sync: true
    matcher:
      files: "src/pages/tokens/**"

  - label: area/dex
    sync: true
    matcher:
      files: "src/pages/dex/**"

  - label: area/address
    sync: true
    matcher:
      files: "src/pages/address/**"

  - label: area/vaults
    sync: true
    matcher:
      files: "src/pages/vaults/**"

  - label: area/auctions
    sync: true
    matcher:
      files: "src/pages/auctions/**"

  - label: area/ocg
    sync: true
    matcher:
      files: "src/pages/ocg/**"

checks:
  - context: "Semantic Pull Request"
    url: "https://github.com/JellyfishSDK/jellyfish/blob/main/.github/labeler.yml"
    description:
      success: Ready for review & merge.
      failure: "Missing semantic title or label for merge [kind(directory): title]"
    labels:
      any:
        - kind/feature
        - kind/fix
        - kind/chore
        - kind/refactor
        - kind/docs
        - kind/dependencies
