# GitHub generic useful labels
- color: c4d471
  name: duplicate
  description: This issue or pull request already exists
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: ffffff
  name: wontfix
  description: This will not be worked on
- color: 000000
  name: stale
  description: No activity for a significant amount of days

# Needs
- color: cc40d8
  name: needs/kind
  description: Needs kind label
- color: cc40d8
  name: needs/area
  description: Needs area label(s)
- color: cc40d8
  name: needs/priority
  description: Needs a priority label
- color: cc40d8
  name: needs/triage
  description: Waiting for triage to be accepted
- color: cc40d8
  name: needs/design
  description: Waiting for design to be implemented

# Kind
- color: e7e9eb
  name: kind/bug
  description: Something isn't working
- color: e7e9eb
  name: kind/feature
  description: New feature request
- color: e7e9eb
  name: kind/question
  description: Generic question
- color: e7e9eb
  name: kind/chore
  description: Non feature change
- color: e7e9eb
  name: kind/fix
  description: Fix a bug
- color: e7e9eb
  name: kind/docs
  description: Non feature documentation change
- color: e7e9eb
  name: kind/refactor
  description: Non feature refactor change
- color: e7e9eb
  name: kind/dependencies
  description: Pull requests that update a dependency file

# Area
- color: fbca04
  name: area/core
- color: fbca04
  name: area/workflow
- color: fbca04
  name: area/public
- color: fbca04
  name: area/layouts
- color: fbca04
  name: area/store
- color: fbca04
  name: area/styles
- color: fbca04
  name: area/blocks
- color: fbca04
  name: area/transactions
- color: fbca04
  name: area/masternodes
- color: fbca04
  name: area/oracles
- color: fbca04
  name: area/tokens
- color: fbca04
  name: area/dex
- color: fbca04
  name: area/ui-ux
- color: fbca04
  name: area/address
- color: fbca04
  name: area/vaults
- color: fbca04
  name: area/auctions
- color: fbca04
  name: area/ocg

# Priority
- color: d93f0b
  name: priority/urgent-now
  description: Urgent fix, as fast as possible
- color: d93f0b
  name: priority/important-soon
  description: Will be important soon

# Triage
- color: b1f488
  name: triage/accepted
  description: Triage has been accepted

# Design
- color: 006B75
  name: design/in-progress
  description: Design in-progress
- color: 006B75
  name: design/ready
  description: Design is ready

# PRD
- color: 2A633E
  name: prd/epic
  description: General overview, broad background. Links to individual stories
- color: 2A633E
  name: prd/story
  description: Actionable features that could be broken down into individual issues