[build]
publish = ".next"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
    [headers.values]
      Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
      Netlify-CDN-Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"