export enum OnChainGovernanceTitles {
  votingCycleTitleWithHash = "Voting Cycle #",
  proposalsSubmittedTitle = "Proposals submitted",
  dfipsTitle = "DFIPS",
  cfpsTitle = "CFPS",
  totalVotesTitle = "Total Votes",
  currentStageTitle = "Current Stage:",
  timeLeftTitle = "Time left:",
  nameOfProposalTitle = "Name of Proposal",
  typeTitle = "Type",
  proposerTitle = "Proposer",
  communityDiscussionTitle = "Community discussions",
  noProposals = "No proposals yet",
  github = "Github",
  reddit = "Reddit",
  voteBreakdownTitle = "Vote Breakdown",
  previousVotingCyclesTitle = "Previous Voting Cycles",
  backToCurrentCycle = "BACK TO CURRENT CYCLE",
  votingCyclesTitle = "Voting Cycles",
  startedTableTitle = "Started",
  endedTableTitle = "Ended",
  cfpTitle = "CFP",
  dfipTitle = "DFIP",
  votingCycleTitle = "Voting Cycle",
  voteResultTitle = "Vote Result",
}
