name: CI - E2E

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 9 * * *'

  pull_request:
    branches: [ main ]

jobs:
  main:
    name: Cypress
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1, 2 ]
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: 15
          cache: 'npm'

      - run: npm ci

      - uses: cypress-io/github-action@6122aa43014e18ec9c2d06fc0bdc5b6759064508
        with:
          install: false
          record: true
          parallel: true
          build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:3000'
          browser: chrome
          spec: cypress/integration/**
          tag: ${{ github.event_name }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: codecov/codecov-action@51d810878be5422784e86451c0e7c14e5860ec47
