name: CI - E2E

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Cypress
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1, 2 ]
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@25316bbc1f10ac9d8798711f44914b1cf3c4e954
        with:
          node-version: 15
          cache: 'npm'

      - run: npm ci

      - uses: cypress-io/github-action@2113e5bc19c45979ba123df6e07256d2aaba9a33
        with:
          install: false
          record: true
          parallel: true
          build: npm run build
          start: npm run dev
          wait-on: 'http://localhost:3000'
          browser: chrome
          spec: cypress/integration/**
          tag: ${{ github.event_name }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: codecov/codecov-action@5a8bb4701eca7ba3673f21664b887f652c58d0a3
