name: CI - E2E

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Cypress
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [ 1, 2, 3, 4, 5 ]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - uses: cypress-io/github-action@53cc3178f59cc99b5519c29c14a182fb98ea4f31
        with:
          config-file: cypress.config.js
          install: false
          record: true
          parallel: true
          build: npm run cypress:build
          start: npm run start
          wait-on: 'http://localhost:3000'
          browser: chrome
          spec: cypress/e2e/**
          tag: ${{ github.event_name }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: codecov/codecov-action@81cd2dc8148241f03f5839d295e000b8f761e378
